let promptList = [{name: "Abominable Snowman", description: ""},
    {name: "Alien", description: ""},
    {name:"Ammit", description: ""},
    {name:"Angelic Abomination", description: ""},
    {name:"Animatronic", description: ""},
    {name:"Baba Yaga", description: ""},
    {name:"Banshee", description: ""},
    {name:"Bat Wings", description: ""},
    {name:"Beauty & the Beast", description: ""},
    {name:"Bedsheet Ghost", description: ""},
    {name:"Belly Mouth", description: ""},
    {name:"Bigfoot", description: ""},
    {name:"Black Widow", description: ""},
    {name:"Bloody Mary", description: ""},
    {name:"Boogie Man", description: ""},
    {name:"Brain", description: ""},
    {name:"Brain & Brawn", description: ""},
    {name:"Bugbear", description: ""},
    {name:"Butler/Maid", description: ""},
    {name:"Candle", description: ""},
    {name:"Cat", description: ""},
    {name:"Cenobite", description: ""},
    {name:"Chained", description: ""},
    {name:"Chimera", description: ""},
    {name:"Chupacabra", description: ""},
    {name:"Clockwork", description: ""},
    {name:"Cockatrice", description: ""},
    {name:"Costumn", description: ""},
    {name:"Covered in Plants", description: ""},
    {name:"Creepy Kid", description: ""},
    {name:"Cthulhu", description: ""},
    {name:"Cyclops", description: ""},
    {name:"Death", description: ""},
    {name:"Deer", description: ""},
    {name:"Devil", description: ""},
    {name:"Dolphin", description: ""},
    {name:"Doppelganger", description: ""},
    {name:"Dragon", description: ""},
    {name:"Dr Jekyll & Mr Hyde", description: ""},
    {name:"Dullahan", description: ""},
    {name:"El Sulbón", description: ""},
    {name:"Elder God", description: ""},
    {name:"Electric Spirit", description: ""},
    {name:"Empty Eye Sockets", description: ""},
    {name:"Evil Overlord", description: ""},
    {name:"Exposed Organs", description: ""},
    {name:"Eyeball Plant", description: ""},
    {name:"Eye Stalks", description: ""},
    {name:"Fairy", description: ""},
    {name:"Fish Humanoid", description: ""}, 
    {name:"Flaming Skull", description: ""},
    {name:"Flatwoods Monster", description: ""},
    {name:"The Fly", description: ""},
    {name:"Fortune Teller", description: ""},
    {name:"Frankenstein", description: ""},
    {name:"Freak Show Attraction", description: ""},
    {name:"From Outerspace", description: ""},
    {name:"Gargoyle", description: ""},
    {name:"Ghost", description: ""},
    {name:"Glowing", description: ""},
    {name:"Gnoll", description: ""},
    {name:"Goatman", description: ""},
    {name:"Golem", description: ""},
    {name:"Greedy", description: ""},
    {name:"Gremlin", description: ""},
    {name:"Griffin", description: ""},
    {name:"Hairy", description: ""},
    {name:"Harpy", description: ""},
    {name:"Hastur", description: ""},
    {name:"Haunted Armor", description: ""},
    {name:"Haunted Tree", description: ""},
    {name:"Haunted Vehicle", description: ""},
    {name:"Headless Horseman", description: ""},
    {name:"Heart", description: ""},
    {name:"Hellhound", description: ""},
    {name:"Hell's Cook", description: ""},
    {name:"Hide-Behind", description: ""},
    {name:"Hitchhiker", description: ""},
    {name:"Hocus", description: "A creature resembling a witches hat with legs. The term for this creature was coined by Jonathan Wojcik, better know as Bogleech, after he noticed there was a lot of decorations of witches hats with legs"},
    {name:"Homunculus", description: ""},
    {name:"Horns", description: ""},
    {name:"Horror Host", description: ""},
    {name:"Horseman of the Apocalypse", description: ""},
    {name:"Insect", description: ""},
    {name:"Invisible", description: ""},
    {name:"Iron Maiden", description: ""},
    {name:"Jabberwocky", description: ""},
    {name:"Jarjacha", description: ""},
    {name:"Jersey Devil", description: ""},
    {name:"Jiang-shi", description: ""},
    {name:"Jorōgumo", description: ""},
    {name:"Kaiju", description: ""},
    {name:"Kappa", description: ""},
    {name:"Karakasa", description: ""},
    {name:"Killer", description: ""},
    {name:"Kitsune", description: ""},
    {name:"Kobold", description: ""},
    {name:"Kraken", description: ""},
    {name:"Krampus", description: ""},
    {name:"La Llorona", description: ""},
    {name:"Living Location", description: ""},
    {name:"Living Shadow", description: ""},
    {name:"Living Statue", description: ""},
    {name:"Loch Ness Monster", description: ""},
    {name:"Long", description: ""},
    {name:"Lovers", description: ""},
    {name:"Lure", description: ""},
    {name:"Mad Scientist", description: ""},
    {name:"Maneating Plant", description: ""},
    {name:"Manticore", description: ""},
    {name:"Mapinguari", description: ""},
    {name:"Mimic", description: ""},
    {name:"Minotaur", description: ""},
    {name:"Mole Men", description: ""},
    {name:"Moloch", description: ""},
    {name:"Monster Biker", description: ""},
    {name:"Moon", description: ""},
    {name:"Moth Man", description: ""},
    {name:"Mummy", description: ""},
    {name:"Mushroom Creature", description: ""},
    {name:"Naga", description: ""},
    {name:"Necromancer", description: ""},
    {name:"Nervous System", description: ""},
    {name:"Nuckelavee", description: ""},
    {name:"Old Cartoon", description: ""},
    {name:"Oni", description: ""},
    {name:"Owl", description: ""},
    {name:"Painting", description: ""},
    {name:"Pandora’s Box", description: ""},
    {name:"Parasite", description: ""},
    {name:"Phantom of the Opera", description: ""},
    {name:"Pig", description: ""},
    {name:"Plague Doctor", description: ""},
    {name:"Pocus", description: "A creature resembling a witches cauldron with legs. The term for this creature was coined by Jonathan Wojcik, better know as Bogleech, after he noticed there was a lot of decorations of cauldrons with legs"},
    {name:"Pollution Monster", description: ""},
    {name:"Poltergeist", description: ""},
    {name:"Possessed Doll", description: ""},
    {name:"Pumpkin", description: ""},
    {name:"Rat", description: ""},
    {name:"Raven/Crow", description: ""},
    {name:"Rawhead and Bloody Bones", description: ""},
    {name:"Robot", description: ""},
    {name:"Roundabout Mouth", description: ""},
    {name:"Scarecrow", description: ""},
    {name:"Sea Monster", description: ""},
    {name:"Shark", description: ""},
    {name:"Sharp Claws", description: ""},
    {name:"Sirenhead", description: ""},
    {name:"Skeleton", description: ""},
    {name:"Slenderman", description: ""},
    {name:"Slime", description: ""},
    {name:"Slit Mouth Woman", description: ""},
    {name:"Smile Dog", description: ""},
    {name:"Spider", description: ""},
    {name:"Spring Heel Jack", description: ""},
    {name:"Stego Spines", description: ""},
    {name:"Stingy Jack", description: ""},
    {name:"Succubus/Inccubus", description: ""},
    {name:"Swamp Creature", description: ""},
    {name:"Sweet Fiends", description: ""},
    {name:"Tentacles", description: ""},
    {name:"Test Tube Creature", description: ""},
    {name:"Toad", description: ""},
    {name:"Toilet Monster", description: ""},
    {name:"Too Many Eyes", description: ""},
    {name:"Too Many Teeth", description: ""},
    {name:"Troll", description: ""},
    {name:"Tsuchinoko", description: ""},
    {name:"Two Headed", description: ""},
    {name:"Umi-Bozu", description: ""},
    {name:"Vampire", description: ""},
    {name:"Voodoo Doll", description: ""},
    {name:"Walking Head", description: ""},
    {name:"Werewolf", description: ""},
    {name:"Will-o'-the-Wisp", description: ""},
    {name:"Witch", description: ""},
    {name:"Worm", description: ""},
    {name:"Yog-Sothoth", description: ""},
    {name:"Yokai", description: ""},
    {name:"Zombie", description: ""},]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    document.getElementById("prompt").innerHTML=prompts[n].name
    document.getElementById("Description").innerHTML=prompts[n].description
}
