let promptList = [{name: "Adze", description: "A Vampiric Firefly from African Mythology"},
    {name: "Akaname", description: "A small Greasy Yokai with a long tongue that cleans filthy areas"},
    {name: "Alien", description: ""},
    {name: "Ammit", description: "An Egyptian monster with the head of a crocodile, the front legs of a lion and hinds of a hippo. She ate the hearts of men who failed judgment."},
    {name: "Angel", description: ""},
    {name: "Animatronic", description: ""},
    {name: "Anubis", description: ""},
    {name: "Apple", description: ""},
    {name: "Azathoth", description: "One of the many outer gods of the Lovecraft Mythos. It is the representation of chaos and therefore has no consistent look."},
    {name: "Baba Yaga", description: "A Slavic witch who flies with a mortar and pestle. She lives in a hut that stands on chicken legs."},
    {name: "Bake-Kujira", description: "A Yokai of a large whale skeleton"},
    {name: "Banshee", description: "An Irish Spirit who is known to scream loudly when someone is about to die"},
    {name: "Baphomet", description: "A demonic winged humanoid with a goat head and a flame above it."},
    {name: "Barber", description: ""},
    {name: "Basilisk", description: "Sometimes known as the cockatrice. A creature that can kill with a single look. Sometimes look like a snake or more like reptilian rooster"},
    {name: "Bat-Winged", description: ""},
    {name: "Bat", description: ""},
    {name: "Beauty & the Beast", description: ""},
    {name: "Belly Jail", description: ""},
    {name: "Belly Mouth", description: ""},
    {name: "Bigfoot", description: ""},
    {name: "Bioluminescent", description: ""},
    {name: "Black Cat", description: ""},
    {name: "Black Shuck", description: "It is a large pitch black dog with a pair of glowing red eyes, though in some versions the Black Shuck has a singular eye like a cyclops."},
    {name: "Black Widow Bride", description: "A woman who marries rich men for their money then murders them"},
    {name: "Black-eyed Children", description: "Strange child-like creatures with pitch black eyes."},
    {name: "Bloody Mary", description: ""},
    {name: "Bodiless Foot", description: ""},
    {name: "Boogie Man", description: ""},
    {name: "Brain Bug", description: ""},
    {name: "Brain and Brawn", description: ""},
    {name: "Brain in a Jar", description: ""},
    {name: "Bride of Frankestien", description: ""},
    {name: "Bugbear", description: "A term for a generic monster and can have a hodgepodge of features. Bugbears can be furry, scaly, slimy, many eyed and more."},
    {name: "Bunyip", description: "A creature from Aboriginal mythology. Though most of the features of the creature are inconsistent from having a dog face to tusk to a horse tail, most agree the creature is aquatic"},
    {name: "Butler/Maid", description: ""},
    {name: "Cactus Cat", description: ""},
    {name: "Car", description: ""},
    {name: "Castle", description: ""},
    {name: "Cat-sidhe", description: "An Irish fairy black cat  with a white spot on its chest and king of cats."},
    {name: "Cenobite", description: "A extra-dimensional demon with a sadistic streak and loves torturing people for pleasure"},
    {name: "Centaur", description: ""},
    {name: "Cerberus", description: ""},
    {name: "Chained", description: ""},
    {name: "Charon", description: "The ferryman who sails the souls of the dead into the underworld in exchange for two coins."},
    {name: "Chef", description: ""},
    {name: "Chimera", description: "A chimera is a monster who is a combination of multiple animals. The classic first Chimera was a combination of a lion, goat and a snake."},
    {name: "Chupacabra", description: ""},
    {name: "Clockwork", description: ""},
    {name: "Clown", description: ""},
    {name: "Coffin", description: ""},
    {name: "Colony", description: ""},
    {name: "Compound Eyes", description: ""},
    {name: "Corpse Candle", description: "A possessed candle with an icy cold flame and can steal the lifeforce of people"},
    {name: "Crystal Creature", description: ""},
    {name: "Cthulhu", description: ""},
    {name: "Cursed Blade", description: ""},
    {name: "Cyborg", description: ""},
    {name: "Cyclops", description: ""},
    {name: "Cóiste Bodhar", description: "Also known as Death’s coach is a thing from Irish folklore said to come when someone is marked for death by the banshee. It will not stop until it has taken one human soul."},
    {name: "Daidarabotchi", description: "Gigantic dark skinned yokai who shape the land as they walk, creating mountains and valleys."},
    {name: "Deer", description: ""},
    {name: "Demon", description: ""},
    {name: "Dinosaur", description: ""},
    {name: "Dodomeki", description: "A Yokai of a human woman whose arms have been covered with hundreds of bird's eyes on her arms due to her habit of stealing."},
    {name: "Dolphin", description: ""},
    {name: "Doomsday Device", description: ""},
    {name: "Doppelganger", description: ""},
    {name: "Double-ended", description: ""},
    {name: "Dr Jekyll & Mr Hyde", description: ""},
    {name: "Dr Moreau's Monsters", description: "Dr Monreau attempt to create a race beastly humanoids out of many animal, although they start out civilized, they eventually return to their feral animal state"},
    {name: "Dragon", description: ""},
    {name: "Dragonborn", description: "They are characterized by their dragon-like features, such as scales, claws, and the ability to breathe fire."},
    {name: "Draugr", description: "Nordic versions of zombies who rise from the dead to wreak havoc on the living if the body hasn’t been put to rest properly"},
    {name: "Drop Bears", description: "A carnivorous koala cryptid that lives in Australia. It drops on prey from the top of trees"},
    {name: "Dullahan", description: "An Irish spirit who is headless spirit who holds their own head and uses a human spine as a whip. Also rides a horse who is of course also headless."},
    {name: "Dungavenhooter", description: "A reptilian cryptid said to hunt specifical drunken lumberjacks. Killing them by smashing them into a fine powder which it then snorts"},
    {name: "Eerie Elevator", description: ""},
    {name: "El Sulbón", description: "A Spirit from Mexico who constantly whistles, with the whistle sounding farther away the closer he is. He carries the bones of his father whom he killed."},
    {name: "Eldritch Horror", description: ""},
    {name: "Elemental Spirit", description: ""},
    {name: "Empty Eye Sockets", description: ""},
    {name: "Evil Minions", description: ""},
    {name: "Evil Overlord", description: ""},
    {name: "Evil Toy", description: ""},
    {name: "Exposed Brains", description: ""},
    {name: "Exposed Organs", description: ""},
    {name: "Eyestalks", description: ""},
    {name: "Fafnir", description: "Was once a noble dwarf who was twisted by his lust for gold over a cursed treasure hoard leading him to killing his father and turning into a dragon"},
    {name: "Fairy", description: ""},
    {name: "Fallen Angel", description: ""},
    {name: "Fenrir", description: "One of the children of Loki, He is an enormous wolf who is said to bring the end of the world."},
    {name: "Fish Men", description: ""},
    {name: "Flatwoods Monster", description: ""},
    {name: "Flaming Skull", description: ""},
    {name: "The Fly", description: ""},
    {name: "Fortune Teller", description: ""},
    {name: "Frankenstien’s Monster", description: ""},
    {name: "Fresno Nightcrawlers", description: "A strange white creature with a small round head upon two legs"},
    {name: "Futakuchi-Onna", description: "A female yokai that appears to be a normal woman but has a secret second mouth on the backside of her head"},
    {name: "Gashadokuro", description: "A gigantic skeleton yokai formed from the bones of dead shoulders and townsfolk"},
    {name: "Gargoyle", description: ""},
    {name: "Genie", description: ""},
    {name: "Ghost", description: ""},
    {name: "Ghost Ship", description: ""},
    {name: "Ghost Train", description: ""},
    {name: "Giant Insects", description: ""},
    {name: "Gibbet", description: "A cage in which prisoners would be put to deter others from crime, usually Pirates."},
    {name: "Gigeresque", description: ""},
    {name: "Gingerbread House", description: ""},
    {name: "Girtablilu", description: "A half human, half scorpion warrior"},
    {name: "Goblin", description: ""},
    {name: "Golem", description: ""},
    {name: "Gorgon", description: ""},
    {name: "Gravedigger", description: ""},
    {name: "Gremlin", description: ""},
    {name: "Griffin", description: ""},
    {name: "Grimoire", description: "A Large book contain magical spells and summonings for demons"},
    {name: "Grim Reaper", description: ""},
    {name: "Guillotine", description: ""},
    {name: "Hacha Nocturna", description: "A headless creature with its rib cage that constantly opens and closes to a dull thud, showing off its beating heart. If you hear it you must follow it and attempt to get the heart within its chest or be cursed for your cowardness"},
    {name: "Hachishaku-Sama", description: "A female yokai also known as Ms. Eight Tall, she wears a white dress with a big white hat. She stalks and kidnap children to kill them"},
    {name: "Hairy", description: ""},
    {name: "Harpy", description: ""},
    {name: "Hastur", description: "As known as the King in Yellow, an eldritch creature who brings madness and is associated with a cursed play. He has no consistent form, but is often depicted wearing a mask and tattered yellow clothes."},
    {name: "Haunted Armor", description: ""},
    {name: "Haunted Hotel", description: ""},
    {name: "Haunted House", description: ""},
    {name: "Haunted Woods", description: ""},
    {name: "Hazmat Suit", description: ""},
    {name: "Head-Hands", description: ""},
    {name: "Headless Horseman", description: ""},
    {name: "Heart", description: ""},
    {name: "Hellhound", description: ""},
    {name: "Hel", description: "A norse goddess of the underworld and one of the children of Loki. She is split in half with one half rotten and dead while one half  is living"},
    {name: "Hidebehind", description: "A cryptid who hunts sober lumberjacks and obviously hides behind stuff."},
    {name: "Hitchhiker", description: ""},
    {name: "Hocus & Pocus", description: "A pair of witches familiars. The hocus is a small witch hat with a pair of leg and a pocus is a similar creature of a bubbling cauldron with legs"},
    {name: "Hodag", description: "A beast born from the rage of abused cows. A green horned spiked back beast and terrible sharp claws"},
    {name: "Homunculus", description: "A small artificial made humanoid created through the process of alchemy"},
    {name: "Hook-Handed Man", description: ""},
    {name: "Horns", description: ""},
    {name: "Horror Show Host", description: ""},
    {name: "Horseman of Conquest", description: ""},
    {name: "Horseman of Death", description: ""},
    {name: "Horseman of Famine", description: ""},
    {name: "Horseman of Pestilence", description: ""},
    {name: "Horseman of War", description: ""},
    {name: "Hydra", description: ""},
    {name: "Igor", description: ""},
    {name: "Inner Jaws", description: "Also known as Pharyngeal jaw, is a second pair of jaws located in the throat"},
    {name: "Invisible", description: ""},
    {name: "Iron Maiden", description: ""},
    {name: "Jackalope", description: ""},
    {name: "Jangsan Beom", description: "Also known as the Jangsan Tiger, it is a cryptid from South Korea. Able to mimic the voice of people including the dead. It's a tiger-like figure cover in long white fur and terrible sharp claws"},
    {name: "Jersey Devil", description: ""},
    {name: "Jiangshi", description: "A vampire from China that can only move by hopping. They often have a paper talisman on their forehead."},
    {name: "Jormungandr", description: "One of Loki's children, an extremely large serpent so big it encircles the earth."},
    {name: "Jorogumo", description: "A Spider Yokai that can shapeshift into a beautiful woman."},
    {name: "Kaiju", description: ""},
    {name: "Kappa", description: "An Aquatic humanoid Yokai with a turtle-like beak and shell. It also has a dish-like dent on top of its head."},
    {name: "Karakasa", description: "An Umbrella yokai with a single eye and leg."},
    {name: "Kasagonagá", description: "A small Multicolored Elephant who is able to control the weather and protects people."},
    {name: "Kasha", description: "A Fiery cat yokai that is known to steal human corpse"},
    {name: "Keukegen", description: ""},
    {name: "Kelpie", description: "A water horse who drags people who ride them underwater"},
    {name: "Khepri", description: "The scarab god who rolled the sun across the sky."},
    {name: "Killer", description: ""},
    {name: "Killer Claw", description: ""},
    {name: "Kitsune", description: ""},
    {name: "Knuckle Walker", description: ""},
    {name: "Kobold", description: ""},
    {name: "Kraken", description: ""},
    {name: "Krampus", description: ""},
    {name: "Krasue", description: "Appears as a woman floating head, with a set of internal organs dangling "},
    {name: "La Llorona", description: "A Mexican spirit that constantly cries and searches for her missing children. Often takes aways other kids she mistakes for hers."},
    {name: "Lake Monster", description: ""},
    {name: "Leshy", description: "A masculan slavic deity of forest"},
    {name: "Lich", description: ""},
    {name: "Living Location", description: ""},
    {name: "Living Shadow", description: ""},
    {name: "Living Statue", description: ""},
    {name: "Lizard Man", description: ""},
    {name: "Local Cryptid", description: "Draw A cryptid from your state, providence, etc."},
    {name: "Loch Ness Monster", description: ""},
    {name: "Long", description: ""},
    {name: "Lovers", description: ""},
    {name: "Lure", description: ""},
    {name: "Mad Scientist", description: ""},
    {name: "Man-Eating Plant", description: ""},
    {name: "Manananggal", description: "a vampire from the Philippines that appears as a woman but is able to separate its upper torso from the lower part of its body and grow wings and fangs."},
    {name: "Mandrake", description: ""},
    {name: "Manticore", description: ""},
    {name: "Mapinguari", description: "A Large sloth-like entity with a single eye and mouth on its belly."},
    {name: "Mask", description: ""},
    {name: "Mech-Organic Mass", description: ""},
    {name: "Mime", description: ""},
    {name: "Mimic", description: ""},
    {name: "Mindflayer", description: ""},
    {name: "Minotaur", description: ""},
    {name: "Mishmash Monsters", description: ""},
    {name: "Mole Men", description: ""},
    {name: "Moloch", description: "A Bull-like deity that children were sacrificed by burning them alive"},
    {name: "Monster Biker", description: ""},
    {name: "Monster Hunter", description: ""},
    {name: "Moon", description: ""},
    {name: "Moth", description: ""},
    {name: "Mummy", description: ""},
    {name: "Mushroom Men", description: ""},
    {name: "Naga", description: ""},
    {name: "Necromancer", description: ""},
    {name: "Ningen", description: "A strange pale creature from the deep that is a hybrid of human an whale"},
    {name: "Nose Horn", description: ""},
    {name: "Nuckelavee", description: "A fleshless horse-like demon with a human torso connected to it where the rider would usually be. The humanoid part has a large head that the neck has trouble supporting it and long arms that reach the ground. It spreads disease wherever it goes, but luckily has a weakness to fresh water."},
    {name: "Nurikabe", description: "A wall Yokai that blocks people from walking forward"},
    {name: "Nurse", description: ""},
    {name: "Nyarlothotep", description: "An eldritch shapeshifter with over 1000 forms though their main disguise is a Dark skinned egyptian pharaoh. Another form is depicted as many tentacle humanoid (including one tentacle head) and a single yellow eye. "},
    {name: "Octopus", description: ""},
    {name: "Ogre", description: ""},
    {name: "Okubi", description: "A yokai who resembles a large human head. That’s really it."},
    {name: "Old Cartoon", description: ""},
    {name: "Oni", description: ""},
    {name: "Orc", description: ""},
    {name: "Otoroshi", description: "A Yokai who sits upon the tops of shinto gates. They have blue skin and are covered in matted hair. They also have sharp claws and boar tusks"},
    {name: "Overgrown", description: ""},
    {name: "Owl", description: ""},
    {name: "Paimon", description: "One of the many demons of hell, depicted as a crowned man riding a camel. He is preceded by a crowd of demons playing musical instruments"},
    {name: "Pandora’s Box", description: ""},
    {name: "Parasite", description: ""},
    {name: "Phantom of the Opera", description: ""},
    {name: "Phoenix", description: ""},
    {name: "Pig", description: ""},
    {name: "Pirate", description: ""},
    {name: "Plague Doctor", description: ""},
    {name: "Poltergeist", description: ""},
    {name: "Possessed Painting", description: ""},
    {name: "Possessed Video Game", description: ""},
    {name: "Prehensile Hair", description: ""},
    {name: "Pumpkin", description: ""},
    {name: "Puppet", description: ""},
    {name: "Rabbit", description: ""},
    {name: "Raiju", description: "A yokai that represents lighting in a beastly form."},
    {name: "Rat", description: ""},
    {name: "Rat King", description: "A Rat king is simply a bunch of rats tangled together by their tails."},
    {name: "Raven/Crow", description: ""},
    {name: "Rawhead and Bloody Bones", description: "A monster that consists of a bloody severed head of a pig and their bones reanimated by a witch."},
    {name: "Ring", description: ""},
    {name: "Robot", description: ""},
    {name: "Roc", description: "An Enormous bird of prey that targets huge prey, from cows to elephants."},
    {name: "Rokurokubi", description: "A yokai that looks like a normal human, except for its incredibly long neck"},
    {name: "Roundabout Mouth", description: ""},
    {name: "Satyr", description: ""},
    {name: "Sazae-Oni", description: "A monstrous snail ogre yokai that can also disguise itself as a beautiful woman in order to lure men."},
    {name: "Scarecrow", description: ""},
    {name: "Scorpion", description: ""},
    {name: "Selkie", description: ""},
    {name: "Set Animal", description: ""},
    {name: "Shark", description: ""},
    {name: "Seemore", description: "Also known as the Peepers, is simply a flower with an eye in it."},
    {name: "Sheet Ghost", description: ""},
    {name: "Shirime", description: "A rather strange yokai with a single eye where its butthole would be."},
    {name: "Shub-Niggurath", description: "Also known as The Black Goat of the Woods with a Thousand Young is One of the many lovecraftian gods. It is a mass of tentacles, Mouths and goat legs that constantly spawns young eldritch gods."},
    {name: "Sickening Goo", description: ""},
    {name: "Sideshow Freak", description: ""},
    {name: "Siren Head", description: ""},
    {name: "Sirens", description: ""},
    {name: "Skeleton", description: ""},
    {name: "Sklider", description: "When a spider becomes a ghost it may possess it bones of various creatures in order to create it own body"},
    {name: "Skunk Ape", description: ""},
    {name: "Slender Man", description: ""},
    {name: "Slime", description: ""},
    {name: "Slit-Mouthed Woman", description: ""},
    {name: "Sluagh", description: "A large crowd of damned souls from Irish folklore."},
    {name: "Smile Dog", description: ""},
    {name: "Smog Monster", description: ""},
    {name: "Snake", description: ""},
    {name: "Snowman", description: ""},
    {name: "Spider", description: ""},
    {name: "Sphinx", description: ""},
    {name: "Split-Jaw", description: ""},
    {name: "Spring Heel Jack", description: "A Demonic specter with a long black cloak and clawed hands, known for its incredible jumping height."},
    {name: "Squid Face", description: ""},
    {name: "Squonk", description: "A cryptid known for its incredible ugliness. It constantly cries and can even turn into a puddle of tears."},
    {name: "Stego Spines", description: ""},
    {name: "Stitched Together", description: ""},
    {name: "Stingy Jack", description: "A drunk who managed to trick the devil and made him promise not to send him to hell. However when he died, he was unable to go to heaven and hell. He was forced to wander the the earth as a spirit carrying a lantern carved plant like a turnip or pumpkin"},
    {name: "Succubus/Incubus", description: ""},
    {name: "Sugar Fiend", description: ""},
    {name: "Sugar Skull", description: ""},
    {name: "Swamp Monster", description: ""},
    {name: "Swarm", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
    // {name: "", description: ""},
]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    document.getElementById("prompt").innerHTML=prompts[n].name
    document.getElementById("description").innerHTML=prompts[n].description
}

// {name: "", description: ""}