let promptList = [{name: "Adze", description: "A Vampiric Firefly from African Mythology"},
    {name: "Akaname", description: "A small Greasy Yokai with a long tongue that cleans filthy areas"},
    {name: "Alien", description: "An unknown creature from the deep recesses of space. Aliens come in all sorts of shapes, from tall, thin, twisted etc."},
    {name: "Ammit", description: "An Egyptian monster with the head of a crocodile, the front legs of a lion and hinds of a hippo. She ate the hearts of men who failed judgment."},
    {name: "Angel", description: ""},
    {name: "Animatronic", description: ""},
    {name: "Apple of Discord", description: "The apple thrown by Eris goddess of chaos"},
    {name: "Asmodeus", description: "One of the demon princes of hell and demon of lust. He has three faces, a bull, a sheep and a human."},
    {name: "Azathoth", description: "One of the many outer gods of the Lovecraft Mythos. It is the representation of chaos and therefore has no consistent look."},
    {name: "Baba Yaga", description: "A Slavic witch who flies with a mortar and pestle. She lives in a hut that stands on chicken legs."},
    {name: "Bake-Kujira", description: "A Yokai of a large whale skeleton"},
    {name: "Banshee", description: "An Irish Spirit who is known to scream loudly when someone is about to die"},
    {name: "Baphomet", description: "A demonic winged humanoid with a goat head and a flame above it."},
    {name: "Barber", description: ""},
    {name: "Basilisk", description: "Sometimes known as the cockatrice. A creature that can kill with a single look. Sometimes look like a snake or more like reptilian rooster"},
    {name: "Bat-Winged", description: ""},
    {name: "Bat", description: ""},
    {name: "Beauty & the Beast", description: ""},
    {name: "Belly Jail", description: ""},
    {name: "Belly Mouth", description: ""},
    {name: "Bigfoot", description: "Also known as the Sasquatch, is a cryptid from the forest of North America. It is a large hairy humanoid"},
    {name: "Bioluminescent", description: ""},
    {name: "Black Cat", description: "They are known to be familiar’s of witches and bring bad luck to people who cross it"},
    {name: "Black Shuck", description: "It is a large pitch black dog with a pair of glowing red eyes, though in some versions the Black Shuck has a singular eye like a cyclops."},
    {name: "Black Widow Bride", description: "A woman who marries rich men for their money then murders them"},
    {name: "Black-eyed Children", description: "Strange child-like creatures with pitch black eyes."},
    {name: "Bloody Mary", description: "A spirit who is said to appear in the mirror if you chant her name three times."},
    {name: "Bodiless Foot", description: ""},
    {name: "Boogie Man", description: "Monstrous beings who spread nightmares to sleeping children"},
    {name: "Brain Bug", description: ""},
    {name: "Brain and Brawn", description: ""},
    {name: "Brain in a Jar", description: ""},
    {name: "Bride of Frankestien", description: ""},
    {name: "Bugbear", description: "A term for a generic monster and can have a hodgepodge of features. Bugbears can be furry, scaly, slimy, many eyed and more."},
    {name: "Bunyip", description: "A creature from Aboriginal mythology. Though most of the features of the creature are inconsistent from having a dog face to tusk to a horse tail, most agree the creature is aquatic"},
    {name: "Butler/Maid", description: ""},
    {name: "Canine", description: ""},
    {name: "Car", description: ""},
    {name: "Castle", description: ""},
    {name: "Cat-sidhe", description: "An Irish fairy black cat  with a white spot on its chest and king of cats."},
    {name: "Cenobite", description: "A extra-dimensional demon with a sadistic streak and loves torturing people for pleasure"},
    {name: "Centaur", description: "A creature with top half being human and the bottom half"},
    {name: "Cerberus", description: "The three headed dog who guards the gate of the underworld."},
    {name: "Chained", description: ""},
    {name: "Charon", description: "The ferryman who sails the souls of the dead into the underworld in exchange for two coins."},
    {name: "Chef", description: ""},
    {name: "Chimera", description: "A chimera is a monster who is a combination of multiple animals. The classic first Chimera was a combination of a lion, goat and a snake."},
    {name: "Chupacabra", description: "A goat blood-sucking monster. It is said to look reptilian with spines along its back."},
    {name: "Clockwork", description: ""},
    {name: "Clown", description: ""},
    {name: "Coffin", description: ""},
    {name: "Colony", description: ""},
    {name: "Compound Eyes", description: ""},
    {name: "Corpse Candle", description: "A possessed candle with an icy cold flame and can steal the lifeforce of people"},
    {name: "Creature From Outer Space", description: ""},
    {name: "Crystal Ball", description: ""},
    {name: "Crystal Creature", description: ""},
    {name: "Cthulhu", description: "A Winged Squid-faced humanoid sleeping in the sunken city of R'lyeh. Nothing can harm him, except for a speeding boat."},
    {name: "Cursed Blade", description: ""},
    {name: "Cyborg", description: ""},
    {name: "Cyclops", description: ""},
    {name: "Cóiste Bodhar", description: "Also known as Death’s coach is a thing from Irish folklore said to come when someone is marked for death by the banshee. It will not stop until it has taken one human soul."},
    {name: "Daidarabotchi", description: "Gigantic dark skinned yokai who shape the land as they walk, creating mountains and valleys."},
    {name: "Deer", description: ""},
    {name: "Demon", description: ""},
    {name: "Dinosaur", description: ""},
    {name: "Dodomeki", description: "A Yokai of a human woman whose arms have been covered with hundreds of bird's eyes on her arms due to her habit of stealing."},
    {name: "Dolphin", description: "Despite their cute appearances, Dolphins can be quite villainous, from torturing Pufferfish to get high off their toxins to killing orca calves just for fun."},
    {name: "Doomsday Device", description: ""},
    {name: "Doppelganger", description: "A strange creature that can mimic people although imperfectly."},
    {name: "Double-ended", description: ""},
    {name: "Dr Jekyll & Mr Hyde", description: "Dr Jekyll is a kind old man, but he has a secret dark side called Mr. Hyde who is cruel and petty."},
    {name: "Dr Moreau's Monsters", description: "Dr Monreau attempt to create a race beastly humanoids out of many animal, although they start out civilized, they eventually return to their feral animal state"},
    {name: "Dragon", description: ""},
    {name: "Dragonborn", description: "They are characterized by their dragon-like features, such as scales, claws, and the ability to breathe fire."},
    {name: "Draugr", description: "Nordic versions of zombies who rise from the dead to wreak havoc on the living if the body hasn’t been put to rest properly"},
    {name: "Drop Bears", description: "A carnivorous koala cryptid that lives in Australia. It drops on prey from the top of trees"},
    {name: "Dullahan", description: "An Irish spirit who is headless spirit who holds their own head and uses a human spine as a whip. Also rides a horse who is of course also headless."},
    {name: "Dungavenhooter", description: "A reptilian cryptid said to hunt specifical drunken lumberjacks. Killing them by smashing them into a fine powder which it then snorts"},
    {name: "Dybbuk", description: "A Malicious spirit that possesses an object or corpse from jewish mythology"},
    {name: "Eerie Elevator", description: ""},
    {name: "El Sulbón", description: "A Spirit from Mexico who constantly whistles, with the whistle sounding farther away the closer he is. He carries the bones of his father whom he killed."},
    {name: "Eldritch Horror", description: ""},
    {name: "Elemental Spirit", description: "Spirits formed of an element like fire or lightning."},
    {name: "Empty Eye Sockets", description: ""},
    {name: "Evil Minions", description: ""},
    {name: "Evil Overlord", description: ""},
    {name: "Evil Toy", description: ""},
    {name: "Exposed Brains", description: ""},
    {name: "Exposed Organs", description: ""},
    {name: "Eyestalks", description: ""},
    {name: "Fafnir", description: "Was once a noble dwarf who was twisted by his lust for gold over a cursed treasure hoard leading him to killing his father and turning into a dragon"},
    {name: "Fairy", description: ""},
    {name: "Fallen Angel", description: ""},
    {name: "Fenrir", description: "One of the children of Loki, He is an enormous wolf who is said to bring the end of the world."},
    {name: "Fish Men", description: ""},
    {name: "Flatwoods Monster", description: "An alien that has a spade shaped hood, a round head with two glowing eyes and a dress/cloak that conceals their legs and thin arms with claws."},
    {name: "Flaming Skull", description: ""},
    {name: "The Fly", description: "The Fly is always a combination of a human and, well, a fly. Sometimes they're human and fly horribly fused together through an experiment. Other times they’re flies that evolved to mimic humans."},
    {name: "Fortune Teller", description: ""},
    {name: "Frankenstien’s Monster", description: "Created by Dr. Frankenstein, the monster is made of various human body parts and brought to life through lighting."},
    {name: "Fresno Nightcrawlers", description: "A strange white creature with a small round head upon two legs"},
    {name: "Futakuchi-Onna", description: "A female yokai that appears to be a normal woman but has a secret second mouth on the backside of her head"}
]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    console.log(prompts[n].name)
    console.log(prompts[n].description)
    document.getElementById("prompt").innerHTML=prompts[n].name
    document.getElementById("description").innerHTML=prompts[n].description
}

// {name: "", description: ""}
